config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html


  # get '/questions', to: 'questions#index'
  # get '/questions/new', to: 'questions#new'
  # get '/questions/:id/edit', to: 'questions#edit'
  # post '/questions', to: 'questions#create'
  # resources :questions, only: %i[index new edit create update destroy show]
  # resources :questions, except: %i[index new edit create update destroy show]
  # resources :questions
  resources :questions do
    # resources :answers
    # resources :answers, only: %i[create destroy]
    resources :answers, except: %i[new show]
  end

  root 'pages#index'
end

app/models/answer.rb
class Answer < ApplicationRecord
  belongs_to :question

  validates :body, presence: true, length: {minimum: 5}

  def formatted_created_at
    created_at.strftime('%Y-%m-%d %H:%M:%S')
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/question.rb
class Question < ApplicationRecord
  has_many :answers, dependent: :destroy

  validates :title, presence: true, length: {minimum: 2}
  validates :body, presence: true, length: {minimum: 2}

  def formatted_created_at
    created_at.strftime('%Y-%m-%d %H:%M:%S')
  end
end

app/controllers/answers_controller.rb
class AnswersController < ApplicationController
  before_action :set_question!
  before_action :set_answer!, except: :create

  def update
    if @answer.update answer_params
      flash[:success] = 'Answer updated!'
      redirect_to question_path(@question)
    else
      render :edit
    end
  end

  def edit
  end

  def create
    # render plain: params
    @answer = @question.answers.build answer_params

    if @answer.save
      flash[:success] = 'Answer created!'
      redirect_to question_path(@question)
    else
      # redirect_to question_path(@question)
      @answers = @question.answers.order created_at: :desc
      render 'questions/show'
    end
  end

  def destroy
    @answer.destroy
    flash[:success] = 'Answer deleted!'
    redirect_to question_path(@question)
  end

  private

  def answer_params
    params.require(:answer).permit(:body)
  end

  def set_question!
    @question = Question.find params[:question_id]
  end

  def set_answer!
    @answer = @question.answers.find params[:id]
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include ErrorHandling
end

app/controllers/concerns/error_handling.rb
module ErrorHandling
  extend ActiveSupport::Concern

  included do
    rescue_from ActiveRecord::RecordNotFound, with: :notfound

    private

    # def notfound
    def notfound(exception)
      # render plain: exception
      # render plain: exception.inspect
      # return

      logger.warn exception
      # send_file 'public/404.html'
      # render file: 'public/404.html', status: :not_found, layout: true
      render file: 'public/404.html', status: :not_found, layout: false
    end
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def index
  end
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  before_action :set_question!, only: %i[show destroy edit update]

  def show
    @answer = @question.answers.build
    @answers = @question.answers.order created_at: :desc
    # @answers = Answer.where(question_id: @question.id).order created_at: :desc
    # @answers = Answer.where(question: @question).order created_at: :desc
  end

  def destroy
    @question.destroy
    flash[:success] = 'Question deleted!'
    redirect_to questions_path
  end

  def edit
  end

  def update
    if @question.update question_params
      flash[:success] = 'Question updated!'
      redirect_to questions_path
    else
      render :edit
      # redirect_to edit_question_path(params[:id])
    end
  end

  def index
    @questions = Question.all
  end

  def new
    @question = Question.new
  end

  def create
    @question = Question.new question_params
    if @question.save
      flash[:success] = 'Question created!'
      redirect_to questions_path
    else
      render :new
      # redirect_to new_question_path
    end
  end

  private

  def question_params
    params.require(:question).permit(:title, :body)
  end

  def set_question!
    # @question = Question.find_by id: params[:id]
    @question = Question.find params[:id]
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def nav_tab(title, url, options = {})
    current_page = options.delete :current_page

    css_class = current_page == title ? 'text-secondary' : 'text-white'

    options[:class] = if options[:class]
                        options[:class] + ' ' + css_class
                      else
                        css_class
                      end

    link_to title, url, options
  end

  def currently_at(current_page = '')
    render partial: 'shared/menu', locals: {current_page: current_page}
  end

  def full_title(page_title = '')
    base_title = 'AskIt'
    if page_title.present?
      "#{page_title} | #{base_title}"
    else
      base_title
    end
  end
end

app/views/answers/_form.html.erb
<%= render 'shared/errors', object: @answer %>

<%= form_with model: [@question, @answer] do |f| %>
  <div class="mb-3 row">
    <div class="col-sm-2 col-form-label">
      <%= f.label :body %>
    </div>

    <div class="col-sm-10">
      <%= f.text_area :body, class: 'form-control' %>
    </div>
  </div>

  <%= f.submit "Submit answer!", class: 'btn btn-primary' %>
<% end %>

app/views/answers/edit.html.erb
<% provide :page_title, 'Edit answer' %>
<% currently_at 'Questions' %>

<h1><%= yield(:page_title) %></h1>

<%= render 'form' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title><%= full_title(yield(:page_title)) %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield :main_menu %>

    <main class="container mt-3">
      <% flash.each do |k, v| %>
        <%= tag.div v, class: "alert alert-#{k}", role: 'alert' %>
      <% end %>

      <%= yield %>
    </main>
  </body>
</html>

app/views/pages/index.html.erb
<% provide :page_title, 'Welcome to AskIt' %>
<% currently_at 'Home' %>

<h1><%= yield(:page_title) %></h1>

&copy; @valpolik <%= Time.now.year %>

app/views/questions/_form.html.erb
<%= render 'shared/errors', object: @question %>

<%= form_with model: @question do |f| %>
  <div class="mb-3 row">
    <div class="col-sm-2 col-form-label">
      <%= f.label :title %>
    </div>

    <div class="col-sm-10">
      <%= f.text_field :title, required: true, placeholder: 'Title', class: 'form-control' %>
    </div>
  </div>

  <div class="mb-3 row">
    <div class="col-sm-2 col-form-label">
      <%= f.label :body %>
    </div>

    <div class="col-sm-10">
      <%= f.text_area :body, required: true, minlength: 2, class: 'form-control' %>
    </div>
  </div>

  <%= f.submit "Submit question!", class: 'btn btn-primary' %>
<% end %>

app/views/questions/edit.html.erb
<% provide :page_title, 'Edit question' %>
<% currently_at 'Questions' %>

<h1 class="mb-4"><%= yield(:page_title) %></h1>

<%= render 'form' %>

app/views/questions/index.html.erb
<% provide :page_title, 'Questions' %>
<% currently_at 'Questions' %>

<h1 class="mb-4"><%= yield(:page_title) %></h1>

<%= link_to 'New question', new_question_path, class: 'btn btn-primary btn-lg' %>

<% @questions.each do |question| %>
  <article class="card mt-3">
    <div class="card-body">
      <h4><%= question.title %></h2>

      <section class="card-text">
        <time datetime="<%= question.formatted_created_at %>">
          <small><%= question.formatted_created_at %></small>
        </time>

        <p class="my-2">
          <%= question.body %>
        </p>
      </section>

      <%= link_to 'Show', question_path(question), class: 'btn btn-primary' %>
      <%= link_to 'Edit', edit_question_path(question), class: 'btn btn-secondary' %>
      <%= link_to 'Destroy', question_path(question), class: 'btn btn-danger',
        data: {method: :delete, confirm: 'Are you sure?'} %>
    </div>
  </article>
<% end %>

app/views/questions/new.html.erb
<% provide :page_title, 'New question' %>
<% currently_at 'Questions' %>

<h1 class="mb-4"><%= yield(:page_title) %></h1>

<%= render 'form' %>

app/views/questions/show.html.erb
<% provide :page_title, @question.title %>
<% currently_at 'Questions' %>

<h1 class="mb-4"><%= yield(:page_title) %></h1>

<time datetime="<%= @question.formatted_created_at %>">
  <%= @question.formatted_created_at %>
</time>

<p class="my-3">
  <%= @question.body %>
</p>

<div class="btn-group">
<%= link_to 'Show', question_path(@question), class: 'btn btn-primary' %>
<%= link_to 'Edit', edit_question_path(@question), class: 'btn btn-secondary' %>
<%= link_to 'Destroy', question_path(@question), class: 'btn btn-danger',
data: {method: :delete, confirm: 'Are you sure?'} %>
</div>

<hr class="my-3">

<h2 class="mb-3">Write your answer</h2>

<%= render 'answers/form' %>

<h2 class="mt-5">Answers</h2>

<% @answers.each do |answer| %>
  <article class="mb-3 card">
    <div class="card-body">
      <section class="card-text">
        <small>
          <time datetime="<%= answer.formatted_created_at %>">
            <%= answer.formatted_created_at %>
          </time>
        </small>

        <p class="mt-2 mb-3">
          <%= answer.body %>
        </p>
      </section>

      <%= link_to 'Edit', edit_question_answer_path(@question, answer),
        class: 'btn btn-info btn-sm' %>

      <%= link_to 'Delete', question_answer_path(@question, answer),
        class: 'btn btn-danger btn-sm',
        data: {method: :delete, confirm: 'Are you sure?'} %>
    </div>
  </article>
<% end %>

app/views/shared/_errors.html.erb
<% if object.errors.full_messages.any? %>
  <div class="alert alert-danger">
    <ul class="mb-0">
      <% object.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_menu.html.erb
<%= provide :main_menu do %>
  <header class="p-3 bg-dark text-white">
    <div class="container">
      <nav class="d-flex flex-wrap align-items-center justify-content-center justify-content-lg-start">
        <ul class="nav col-12 col-lg-auto me-lg-auto mb-2 justify-content-center mb-md-0">
          <li><%= nav_tab 'Home', root_path,
            class: 'nav-link px-2', current_page: current_page %></li>
          <li><%= nav_tab 'Questions', questions_path,
            class: 'nav-link px-2', current_page: current_page %></li>
        </ul>
      </nav>
    </div>
  </header>
<% end %>